### ISSUE TITLE
Hardcoded value in the `/catalog` endpoint

### ISSUE THREAD

**Issue by csavelief** [computablefacts/towerify#4]
Replace the hardcoded "super-admin" email in the `/catalog` endpoint with the value from the `ADMIN_EMAIL` environment variable.

**Comment by PatBriPerso** [comment]
We talk about this route in web.php?
`Route::post('metrics', function (\Illuminate\Http\Request $request) {/*...*/})`

I do not find any hardcoded email :thinking:

**Comment by csavelief** [comment]
My bad! It was the `/catalog` endpoint...

![image](https://github.com/computablefacts/towerify/assets/870947/725bcb97-b0b9-4c16-a76c-782f065f9c33)
